services:
  # Servicio de la Base de Datos
  - name: postgres-db-analizador
    type: pserv
    plan: free

  # Servicio del Backend (nuestra aplicación)
  - name: analizador-web-backend
    type: web
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromService:
          name: postgres-db-analizador
          type: pserv
          property: connectionString
      - key: SECRET_KEY
        sync: false
